x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.roborsi:/root/.roborsi

services:
  roborsi-web:
    container_name: roborsi-web
    <<: *common-config
    command: ["web", "--host", "0.0.0.0"]
    restart: unless-stopped
    ports:
      - 8787:8787
      - 8795:8795
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
  
  roborsi-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
