"""Planner-authored zero-shot skill synthesis.

When a sim task has an env but NO roborsi skill (no skills/atomic/<task>/ or
long_horizon/<task>/), the 3-role pipeline rejects it ("no runnable <task>.zeroshot
exists"), so 43 of the 50 RoboTwin tasks could not run. Instead, the Planner now
AUTHORS the skill itself from the requested task and public skill vocabulary,
then returns a short task understanding; we assemble the
canonical `<task>.zeroshot` SKILL.md + the 1-line boilerplate policy.py
(run_zeroshot_diagnostic) and validate it registers.

Sibling of env_synthesizer — the Manager only reviews/approves. The boilerplate
policy.py is deterministic; the *intelligence* is the Planner's task instruction
(and the plan.md recipe written live during the run).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_ATOMIC_ROOT = _REPO / "roborsi" / "embodied" / "skills" / "atomic"
_LH_ROOT = _REPO / "roborsi" / "embodied" / "skills" / "long_horizon"

_SKILL_AUTHOR_SYSTEM = (
    "You author the task understanding for a RoboTwin sim atomic task that has a "
    "sim env but no runnable roborsi skill yet. Work only from the user's task "
    "request, the task name, visible observations available during execution, "
    "and RoboRSI's public skill vocabulary. Do not inspect simulator task source, "
    "scripted experts, hidden object state, or hidden success criteria. Return "
    "STRICT JSON (no prose, no fences) with "
    "exactly:\n"
    '  {"description": "<one line: what the skill does>",\n'
    '   "instruction": "<2-4 sentences telling the Engineer the goal + concrete '
    "objects + a perception-first approach (perceive, ground, grasp/move/place), "
    'phrased for VLM+base-tools execution>",\n'
    '   "expected_on_success": "<one line: a visible completion condition>"}\n'
    "The harness records the simulator verdict only after execution; do not try "
    "to infer or reproduce its hidden implementation."
)

_POLICY_TEMPLATE = '''"""{task}.zeroshot — auto-authored zero-shot atomic skill.

Generated by agents/skill_synthesizer.py because {task} had a sim env but no
runnable roborsi skill. Boilerplate: drive one VLM rollout episode against
the task's env via the shared run_zeroshot_diagnostic; the task instruction +
visible completion description live in SKILL.md, and the recipe accrues in plan.md.
"""
from __future__ import annotations

from typing import Any

from roborsi.embodied.skills._lib.standalone_atomic import (
    run_zeroshot_diagnostic,
)


def run(env=None, **kwargs: Any) -> dict[str, Any]:
    return run_zeroshot_diagnostic("{task}", env=env, **kwargs)
'''


def skill_exists(task: str) -> bool:
    """True iff a USABLE skill is present. For an atomic that means the PARENT
    ``SKILL.md`` exists — the doc ``_prompts_for`` (via ``get_skill``) reads for
    the task instruction. A bare directory with only a half-written ``zeroshot/``
    but no parent ``SKILL.md`` makes ``_prompts_for`` RAISE (the Engineer then
    runs with no real instruction and flails), so we treat that as MISSING and
    let synthesis re-author/heal the parent. LH skills are just a directory."""
    if (_LH_ROOT / task).is_dir():
        return True
    parent = _ATOMIC_ROOT / task
    # Need BOTH the parent SKILL.md (for _prompts_for) AND a loadable
    # <task>.zeroshot subskill (policy.py). A parent that only has
    # eval/train/reset_* subskills — a demo/train task like
    # stack_bowls_bicoord — HAS a SKILL.md but no zeroshot/, so cli_3role's
    # `<task>.zeroshot` lookup raises "unknown skill". Treat that as MISSING
    # so synthesis authors the zeroshot boilerplate instead of skipping.
    return (parent / "SKILL.md").exists() and (parent / "zeroshot" / "policy.py").exists()


def _parent_skill_md(task: str, description: str, instruction: str,
                     expected: str) -> str:
    """Parent skills/atomic/<task>/SKILL.md — what _prompts_for reads."""
    def lit(s: str) -> str:
        return s.replace("\n", " ").strip()
    return (
        "---\n"
        f"name: {task}\n"
        "kind: atomic\n"
        "robot: robotwin\n"
        "category: manipulation\n"
        "version: 0.1.0\n"
        f"description: {lit(description)}\n"
        "metadata:\n"
        "  tags: [atomic, sim, robotwin, auto-authored]\n"
        "  vlm_prompts:\n"
        f"    instruction: \"{lit(instruction)}\"\n"
        f"    expected_on_success: \"{lit(expected)}\"\n"
        "---\n\n"
        f"# {task}\n\n"
        f"Auto-authored atomic skill for `{task}`.\n\n"
        f"**Goal:** {lit(instruction)}\n\n"
        f"**Success:** {lit(expected)}\n"
    )


def _child_skill_md(task: str, description: str) -> str:
    """Child skills/atomic/<task>/zeroshot/SKILL.md — the runnable subskill."""
    def lit(s: str) -> str:
        return s.replace("\n", " ").strip()
    return (
        "---\n"
        f"name: {task}.zeroshot\n"
        "kind: atomic_subskill\n"
        f"parent: {task}\n"
        "phase: zeroshot\n"
        "version: 0.1.0\n"
        f"description: VLM zero-shot attempt at {task}. {lit(description)}\n"
        "metadata:\n"
        "  tags: [zeroshot, vlm, sim, robotwin, auto-authored]\n"
        "params:\n"
        "  episodes:    { type: int, default: 1 }\n"
        "  seed_start:  { type: int, default: 0 }\n"
        "  tool_budget: { type: int, default: 25 }\n"
        "---\n\n"
        f"# {task}.zeroshot\n\n"
        f"Runnable zero-shot entry for `{task}` — drives one VLM rollout episode.\n"
    )


def _extract_json(text: str) -> dict | None:
    t = (text or "").strip()
    m = re.search(r"\{.*\}", t, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError:
        return None


def _validate_registers(task: str) -> bool:
    """The new <task>.zeroshot must be discoverable with usable prompts."""
    from roborsi.embodied.skills import get as get_skill
    from roborsi.embodied.skills._lib.standalone_atomic import _prompts_for
    sk = get_skill(f"{task}.zeroshot") or get_skill(task)
    if sk is None:
        return False
    instr, _exp = _prompts_for(task)
    return bool(instr and instr.strip())


def synthesize_skill_if_missing(task: str) -> tuple[bool, str]:
    """Ensure task has a runnable roborsi skill; if not, scaffold the missing
    ``<task>.zeroshot``. Two paths:
      1. the parent SKILL.md already exists with a usable instruction (a
         demo/train task like stack_bowls_bicoord that only lacks its zeroshot
         boilerplate) — drop in the 1-line policy.py, no Planner round-trip;
      2. no parent — the Planner authors the task understanding from the public
         request and we assemble the full skill.
    Returns (ok, message). Caller should have already ensured the env exists."""
    from roborsi.agents import persistent_agent
    if skill_exists(task):
        return True, "exists"
    parent_dir = _ATOMIC_ROOT / task
    parent_md = parent_dir / "SKILL.md"
    skill_dir = parent_dir / "zeroshot"
    # Path 1 — parent SKILL.md present (its sim_task / vlm_prompts / lifecycle
    # are all there); it only lacks the runnable zeroshot subskill. Scaffold the
    # boilerplate WITHOUT touching the parent, so sim_task etc. survive.
    if parent_md.exists():
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "policy.py").write_text(
            _POLICY_TEMPLATE.format(task=task), encoding="utf-8")
        if not (skill_dir / "SKILL.md").exists():
            (skill_dir / "SKILL.md").write_text(
                _child_skill_md(task, f"zero-shot {task}"), encoding="utf-8")
        if _validate_registers(task):
            return True, "scaffolded <task>.zeroshot onto existing parent SKILL.md"
        for f in (skill_dir / "policy.py", skill_dir / "SKILL.md"):
            if f.exists():
                f.unlink()
        try:
            skill_dir.rmdir()
        except OSError:
            pass
        return False, f"scaffolded {task}.zeroshot but it did not register"
    # Path 2 — no parent: Planner authors from the public task request.
    prompt = (
        f"Task '{task}' has a sim env but NO runnable roborsi skill, so the "
        f"3-role pipeline rejects it. Author a perception-first task understanding "
        f"from the task request/name and the public RoboRSI skill vocabulary. "
        f"Execution will refine the plan from camera observations and tool results. "
        f"Return the strict JSON described."
    )
    resp = persistent_agent.run("skill_author", task, prompt,
                                system_prompt=_SKILL_AUTHOR_SYSTEM)
    spec = _extract_json(resp)
    if not spec or "instruction" not in spec:
        return False, f"Planner returned no usable task spec for {task}"
    desc = spec.get("description", f"zero-shot {task}")
    instr = spec["instruction"]
    exp = spec.get("expected_on_success", "task visually complete")
    parent_dir = _ATOMIC_ROOT / task
    skill_dir = parent_dir / "zeroshot"
    skill_dir.mkdir(parents=True, exist_ok=True)
    (parent_dir / "SKILL.md").write_text(
        _parent_skill_md(task, desc, instr, exp), encoding="utf-8")
    (skill_dir / "policy.py").write_text(
        _POLICY_TEMPLATE.format(task=task), encoding="utf-8")
    (skill_dir / "SKILL.md").write_text(
        _child_skill_md(task, desc), encoding="utf-8")
    if _validate_registers(task):
        return True, "authored by Planner (parent + <task>.zeroshot)"
    # roll back a non-registering skill so it doesn't half-exist
    for f in (skill_dir / "policy.py", skill_dir / "SKILL.md",
              parent_dir / "SKILL.md"):
        if f.exists():
            f.unlink()
    for d in (skill_dir, parent_dir):
        try:
            d.rmdir()
        except OSError:
            pass
    return False, f"authored {task} skill but it did not register"
