"""roborsi.agent.lifecycle.scaffold — `atomic new <name>`.

Generates a fully-functional atomic skill from a brief spec. Output matches
the existing pick_block_bicoord / pick_and_place_at_pixel structure so the
data flywheel can run on it without further edits.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .atomic import SKILLS_ROOT


def scaffold_atomic(
    task_name: str,
    sim_task: str,
    backend: str = "bicoord",
    spec: str = "",
    judge_criterion: str = "",
    overwrite: bool = False,
) -> dict[str, Any]:
    """Create skills/atomic/<task_name>/{SKILL.md, zeroshot/, train/, eval/,
    reset_success/, reset_failure/, judge/} populated with working policy.py
    files.

    Args:
        task_name: atomic task name (will become the dir name + SKILL.md `name`)
        sim_task: BiCoord/RoboTwin task to spawn
        backend: bicoord / robotwin / robotwin-http
        spec: natural-language description of what the atomic does
            (becomes the VLM zeroshot instruction + atomic SKILL.md description)
        judge_criterion: what counts as success — the judge's prompt
        overwrite: if True, overwrite existing files

    Returns:
        dict with files written + state.
    """
    if not task_name:
        raise ValueError("task_name is required")
    if not sim_task:
        raise ValueError("sim_task is required")
    spec = spec or f"Complete the {task_name.replace('_', ' ')} task in BiCoord."
    judge_criterion = judge_criterion or (
        f"The {task_name.replace('_', ' ')} task is visibly accomplished in the post image."
    )

    atomic_dir = SKILLS_ROOT / "atomic" / task_name
    if atomic_dir.exists() and not overwrite:
        return {"ok": False, "reason": f"{atomic_dir} already exists; pass overwrite=True"}
    atomic_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    def _write(rel: str, content: str) -> None:
        path = atomic_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(str(path.relative_to(SKILLS_ROOT.parent)))

    # Top-level SKILL.md
    _write("SKILL.md", _atomic_skill_md(task_name, spec, sim_task, backend))

    # zeroshot
    _write("zeroshot/SKILL.md", _phase_skill_md(task_name, "zeroshot",
        f"VLM tool-loop attempt at {task_name}."))
    _write("zeroshot/policy.py", _zeroshot_policy(task_name, spec))

    # train
    _write("train/SKILL.md", _phase_skill_md(task_name, "train",
        f"Build LeRobot v3 dataset + finetune ACT/π0 from {task_name} successes."))
    _write("train/policy.py", _train_policy(task_name))

    # eval
    _write("eval/SKILL.md", _phase_skill_md(task_name, "eval",
        f"Evaluate latest {task_name} ckpt; flip active_executor at threshold."))
    _write("eval/policy.py", _eval_policy(task_name, sim_task, backend))

    # reset_success
    _write("reset_success/SKILL.md", _phase_skill_md(task_name, "reset_success",
        f"After successful {task_name} episode, reset for next."))
    _write("reset_success/policy.py", _reset_success_policy(task_name, backend))

    # reset_failure
    _write("reset_failure/SKILL.md", _phase_skill_md(task_name, "reset_failure",
        f"After failed {task_name} episode, classify mode + recover."))
    _write("reset_failure/policy.py", _reset_failure_policy(task_name, backend))

    # judge
    _write("judge/SKILL.md", _phase_skill_md(task_name, "judge",
        f"Claude-subprocess VLM judge of one {task_name} attempt."))
    _write("judge/policy.py", _judge_policy(task_name, judge_criterion))

    return {"ok": True, "task": task_name, "dir": str(atomic_dir),
            "files": written, "next_state": "SCAFFOLDED"}


def _atomic_skill_md(task: str, spec: str, sim_task: str, backend: str) -> str:
    pretty = task.replace("_", " ")
    return f"""---
name: {task}
kind: atomic
domain: manipulation
version: 0.1.0
description: {spec}
metadata:
  tags: [atomic, sim, {backend}]
  embodiments: [aloha-agilex]
  backends: [{backend}]
  sim_task: {sim_task}
  vlm_prompts:
    instruction: "{spec}"
    expected_on_success: "{pretty} accomplished and visible in the post image."
  active_executor:
    default: zeroshot
    threshold: 0.40
---

# {task} (atomic)

Generated by `roborsi atomic new {task}`. 6 sub-skills follow the standard
RoboRSI lifecycle: zeroshot collects via VLM+tool, train builds a LeRobot
dataset and finetunes ACT, eval flips active_executor at threshold,
reset_success / reset_failure handle scene reset, judge is the per-trajectory
VLM judge.
"""


def _phase_skill_md(task: str, phase: str, summary: str) -> str:
    return f"""---
name: {task}.{phase}
kind: atomic_subskill
parent: {task}
phase: {phase}
description: {summary}
---
"""


def _zeroshot_policy(task: str, spec: str) -> str:
    return f'''"""atomic.{task}.zeroshot — VLM tool-loop attempt."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from roborsi.data.store import DataStore
from roborsi.embodied.agent_loop.rollout import run_rollout


_SKILL = "{task}"


def run(
    env=None,
    task_name: str = _SKILL,
    tool_budget: int = 25,
    model: str | None = None,
    workdir: str | None = None,
    seed: int | None = None,
    log: bool = True,
    **_: Any,
) -> dict[str, Any]:
    if env is None:
        raise ValueError(f"{{_SKILL}}.zeroshot requires a live env (long_horizon mode)")

    instruction = (
        "{spec} "
        "Use the standard rollout tool repertoire (look, find_pixel, get_object_bbox, "
        "zoom_in, unproject_pixel, move_to_pixel, move_to_pose, gripper). For tiny "
        "objects, prefer get_object_bbox (auto-zooms) over find_pixel. After grasp, "
        "ALWAYS release before calling done. "
        "Call done(success=true) only when the success criterion is visibly met."
    )
    expected = "Task accomplished and visible in the post image."

    work = Path(workdir).expanduser() if workdir else Path("/tmp/roborsi-zeroshot/{task}")
    result = run_rollout(
        env, seed=int(seed or 0), task_name=task_name,
        instruction=instruction, expected_on_success=expected,
        model=model, tool_budget=tool_budget, workdir=work,
    )
    rollout = result.rollout
    rollout.meta.setdefault("collector", "zeroshot")
    written = DataStore().write(
        rollout, skill=task_name,
        extra_meta={{"subskill": f"atomic.{{_SKILL}}.zeroshot"}},
    ) if log and rollout.success else None
    return {{
        "skill": f"atomic.{{_SKILL}}.zeroshot",
        "task_name": task_name,
        "success": rollout.success,
        "outcome": rollout.outcome,
        "tool_calls": rollout.meta.get("tool_calls"),
        "vlm_trace": result.trace,
        "run_id": written.run_id if written else None,
    }}
'''


def _train_policy(task: str) -> str:
    return f'''"""atomic.{task}.train — build dataset + finetune ACT."""

from __future__ import annotations

from typing import Any

from roborsi.embodied.skills import run as run_skill


_SKILL = "{task}"


def run(
    base_model: str = "act",
    steps: int = 2000,
    batch_size: int = 4,
    lr: float = 5e-5,
    dataset_name: str = "{task}_v1",
    **_: Any,
) -> dict[str, Any]:
    ds_result = run_skill(
        "lerobot_build", skill_label=_SKILL, dataset_name=dataset_name,
    )
    repo_id = dataset_name if "/" in dataset_name else f"local/{{dataset_name}}"
    ckpt_result = run_skill(
        "pi0_finetune", dataset=repo_id, base_model=base_model,
        steps=steps, batch_size=batch_size, lr=lr,
    )
    return {{
        "skill": f"atomic.{{_SKILL}}.train",
        "dataset_root": ds_result.get("root"),
        "dataset_episodes": ds_result.get("episodes"),
        "checkpoint": ckpt_result.get("output_dir"),
        "last_log": ckpt_result.get("last_log"),
    }}
'''


def _eval_policy(task: str, sim_task: str, backend: str) -> str:
    return f'''"""atomic.{task}.eval — eval + active_executor switch."""

from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Any

from roborsi.embodied.paths import home as _home_dir
from roborsi.embodied.skills import run as run_skill


_ATOMIC = "{task}"
_SIM_TASK = "{sim_task}"
_BACKEND = "{backend}"


def run(
    seeds: int = 5,
    seed_start: int = 1000,
    threshold: float = 0.40,
    checkpoint: str | None = None,
    executor: str = "pi0_checkpoint",
    **_: Any,
) -> dict[str, Any]:
    if executor == "pi0_checkpoint" and not checkpoint:
        checkpoint = _latest_checkpoint(_ATOMIC)
        if not checkpoint:
            raise RuntimeError(f"no checkpoint found for {{_ATOMIC}}")
    eval_result = run_skill(
        "success_rate", task=_SIM_TASK, backend=_BACKEND,
        executor=executor, seeds=seeds, seed_start=seed_start,
        checkpoint=checkpoint,
    )
    rate = float(eval_result.get("success_rate", 0.0))
    switched = rate >= threshold and executor == "pi0_checkpoint"
    if switched:
        _write_active_executor(_ATOMIC, f"policy:{{checkpoint}}", rate)
    return {{
        "skill": f"atomic.{{_ATOMIC}}.eval",
        "atomic": _ATOMIC, "sim_task": _SIM_TASK, "backend": _BACKEND,
        "executor": executor, "checkpoint": checkpoint, "seeds": seeds,
        "successes": eval_result.get("successes"),
        "success_rate": rate, "threshold": threshold,
        "switched": switched, "report_path": eval_result.get("report_path"),
    }}


def _latest_checkpoint(atomic: str) -> str | None:
    root = _home_dir() / "checkpoints"
    if not root.exists():
        return None
    candidates = [p for p in root.rglob("pretrained_model") if atomic in str(p)]
    return str(max(candidates, key=lambda p: p.stat().st_mtime)) if candidates else None


def _write_active_executor(atomic: str, executor: str, rate: float) -> None:
    path = _home_dir() / "atomic_state" / atomic / "active_executor.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({{
        "task": atomic, "executor": executor,
        "since_ts": time.time(), "success_rate": rate,
    }}, indent=2), encoding="utf-8")
'''


def _reset_success_policy(task: str, backend: str) -> str:
    return f'''"""atomic.{task}.reset_success — env.reset + log."""

from __future__ import annotations

from typing import Any

from roborsi.data.store import DataStore
from roborsi.embodied.agent_loop.env import Rollout, Step, Observation


_TASK = "{task}"
_LABEL = "{task}_reset_success"


def run(env=None, next_seed: int | None = None, log: bool = True, **_: Any) -> dict[str, Any]:
    if env is None:
        return {{"ok": True, "skipped": "no env provided"}}
    pre = _safe_obs(env)
    if next_seed is not None:
        env.reset(next_seed)
    else:
        impl = env._impl
        if impl is not None:
            impl.robot.move_to_homestate()
            impl.together_open_gripper(left_pos=1, right_pos=1)
    post = _safe_obs(env)
    if log:
        roll = Rollout(
            task=_TASK, seed=next_seed or -1,
            success=True, outcome="reset",
            meta={{"backend": "{backend}", "subskill": "reset_success"}},
        )
        roll.steps.append(Step(obs=pre, info={{"phase": "pre_reset"}}))
        roll.steps.append(Step(obs=post, info={{"phase": "post_reset"}}))
        DataStore().write(roll, skill=_LABEL,
                          extra_meta={{"reset_kind": "success", "next_seed": next_seed}})
    return {{"ok": True, "logged": log}}


def _safe_obs(env) -> Observation:
    impl = getattr(env, "_impl", None)
    if impl is None:
        return Observation()
    from roborsi.embodied.sim.robotwin.adapter import _to_sim_obs
    return _to_sim_obs(impl.get_obs())
'''


def _reset_failure_policy(task: str, backend: str) -> str:
    return f'''"""atomic.{task}.reset_failure — failure recover + log."""

from __future__ import annotations

from typing import Any

from roborsi.data.store import DataStore
from roborsi.embodied.agent_loop.env import Rollout, Step, Observation


_TASK = "{task}"
_LABEL_PREFIX = "{task}_reset_failure"


def run(env=None, next_seed: int | None = None,
        failure_mode_hint: str | None = None, **_: Any) -> dict[str, Any]:
    if env is None:
        return {{"ok": False, "reason": "no env"}}
    impl = env._impl
    pre_obs = _safe_obs(env)
    mode = failure_mode_hint or "unknown"
    if next_seed is not None:
        env.reset(next_seed)
    else:
        impl.robot.move_to_homestate()
        impl.together_open_gripper(left_pos=1, right_pos=1)
    post_obs = _safe_obs(env)
    roll = Rollout(
        task=_TASK, seed=next_seed or -1,
        success=True, outcome="recovered",
        meta={{"backend": "{backend}", "subskill": "reset_failure", "mode": mode}},
    )
    roll.steps.append(Step(obs=pre_obs, info={{"phase": "pre_recovery", "mode": mode}}))
    roll.steps.append(Step(obs=post_obs, info={{"phase": "post_recovery"}}))
    DataStore().write(roll, skill=f"{{_LABEL_PREFIX}}_{{mode}}",
                      extra_meta={{"reset_kind": "failure", "mode": mode, "next_seed": next_seed}})
    return {{"ok": True, "failure_mode": mode}}


def _safe_obs(env) -> Observation:
    impl = getattr(env, "_impl", None)
    if impl is None:
        return Observation()
    from roborsi.embodied.sim.robotwin.adapter import _to_sim_obs
    return _to_sim_obs(impl.get_obs())
'''


def _judge_policy(task: str, criterion: str) -> str:
    return f'''"""atomic.{task}.judge — Claude-subprocess VLM judge."""

from __future__ import annotations

from typing import Any

from roborsi.embodied.skills import run as run_skill


def run(pre_image: str | None = None, post_image: str | None = None, **_: Any) -> dict[str, Any]:
    if not post_image:
        return {{"success": False, "reason": "no post_image"}}
    criterion = (
        "{criterion}"
    )
    images = [p for p in [pre_image, post_image] if p]
    judged = run_skill("vlm_judge_claude", criterion=criterion, images=images,
                       context="atomic={task}")
    return {{
        "skill": "atomic.{task}.judge",
        "success": bool(judged.get("success")),
        "reason": judged.get("reason"),
    }}
'''
