"""shake_bottle_horizontally.zeroshot — auto-authored zero-shot atomic skill.

Generated by agents/skill_synthesizer.py because shake_bottle_horizontally had a sim env but no
runnable roborsi skill. Boilerplate: drive one VLM rollout episode against
the task's env via the shared run_zeroshot_diagnostic; the task instruction +
success predicate live in SKILL.md, the recipe accrues in plan.md.

NOTE: shake_bottle_horizontally's sim env ships in the RoboTwin repo
the simulator task implementation, NOT in
the BiCoord-Bench fork. run_zeroshot_diagnostic defaults backend="bicoord",
whose task_root has no shake_bottle_horizontally.py, so the import raises
BackendUnavailable. This skill's SKILL.md frontmatter declares
`robot: robotwin`, so we pin backend="robotwin" here.
"""
from __future__ import annotations

from typing import Any

from roborsi.embodied.skills._lib.standalone_atomic import (
    run_zeroshot_diagnostic,
)


def run(env=None, **kwargs: Any) -> dict[str, Any]:
    kwargs.setdefault("backend", "robotwin")
    return run_zeroshot_diagnostic("shake_bottle_horizontally", env=env, **kwargs)
