"""stack_bowls_bicoord.zeroshot — auto-authored zero-shot atomic skill.

Generated by agents/skill_synthesizer.py because stack_bowls_bicoord had a sim env but no
runnable roborsi skill. Boilerplate: drive one VLM rollout episode against
the task's env via the shared run_zeroshot_diagnostic; the task instruction +
success predicate live in SKILL.md, the recipe accrues in plan.md.
"""
from __future__ import annotations

from typing import Any

from roborsi.embodied.skills._lib.standalone_atomic import (
    run_zeroshot_diagnostic,
)


def run(env=None, **kwargs: Any) -> dict[str, Any]:
    return run_zeroshot_diagnostic("stack_bowls_bicoord", env=env, **kwargs)
